version: '2'
services:
    bb_blog-app:
        image: bb_blog
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bb_blog-mysql:3306/bb_blog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bb_blog-mysql:
        extends:
            file: mysql.yml
            service: bb_blog-mysql
